name: Ejercicio github actions

on:
  schedule:
    - cron: '0 0 * * 1' # Ejecutar la acción cada lunes
  workflow_dispatch: # Permite ejecutarla manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate GitHub Metrics
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Utiliza el token de tu repositorio
        plugin_languages: yes # Activa el plugin de lenguajes
        config_timezone: Europe/Madrid # Configura la zona horaria
